# sass-lint config to match the AirBNB style guide
# See silverstripe-admin
files:
  include: '**/client/src/**/*.scss'
  ignore:
    - 'client/src/styles/legacy/*'
    - 'src/**/*'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  # Warnings
  # Things that require actual refactoring are marked as warnings
  class-name-format:
    - 1
    - convention: hyphenatedbem
  placeholder-name-format:
    - 1
    - convention: hyphenatedlowercase
  nesting-depth:
    - 1
    - max-depth: 3
  no-ids: 1
  no-important: 1
  no-misspelled-properties:
    - 1
    - extra-properties:
       - "-moz-border-radius-topleft"
       - "-moz-border-radius-topright"
       - "-moz-border-radius-bottomleft"
       - "-moz-border-radius-bottomright"
  variable-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  no-extends: 1

  # Warnings: these things are preferential rather than mandatory
  no-css-comments: 1

  # Errors
  # Things that can be easily fixed are marked as errors
  indentation:
    - 2
    - size: 2
  final-newline:
    - 2
    - include: true
  no-trailing-whitespace: 2
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - allow-single-line: true
  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false
  no-debug: 2
  no-empty-rulesets: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  # no-qualifying-elements:
  #   - 1
  #   - allow-element-with-attribute: false
  #     allow-element-with-class: false
  #     allow-element-with-id: false
  no-trailing-zero: 2
  no-url-protocols: 2
  quotes:
    - 2
    - style: double
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 2
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  zero-unit: 2
  single-line-per-selector: 2
  one-declaration-per-line: 2
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: true