// This file was generated by silverstripe/cow from javascript/lang/src/en.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "Workflow.DeleteQuestion": "Are you sure you want to permanently delete this?",
    "Workflow.EMBARGOMESSAGEDATE": "Saved drafts of this page will auto publish on <a>%s<\/a>",
    "Workflow.EMBARGOMESSAGEDATETIME": "Saved drafts of this page will auto publish on <a>%s at %s<\/a>",
    "Workflow.EMBARGOMESSAGETIME": "Saved drafts of this page will auto publish today at <a>%s<\/a>",
    "Workflow.ProcessError": "Could not process workflow"
});
}