// This file was generated by silverstripe/cow from client/lang/src/eo.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "Workflow.DeleteQuestion": "Ĉi vi vere volas porĉiame forigi ĉi tiun dosieron?",
    "Workflow.EMBARGOMESSAGEDATE": "Konservitaj malnetoj de la paĝo aŭtomate publikiĝos je <a>%s</a>",
    "Workflow.EMBARGOMESSAGEDATETIME": "Konservitaj malnetoj de la paĝo aŭtomate publikiĝos ĉe <a>%s je %s</a>",
    "Workflow.EMBARGOMESSAGETIME": "Konservitaj malnetoj de la paĝo aŭtomate publikiĝos hodiaŭ je  <a>%s</a>",
    "Workflow.ProcessError": "Ne povis trakti la laborfluon"
});
}