// This file was generated by silverstripe/cow from client/lang/src/es.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('es', {
    "Workflow.DeleteQuestion": "¿Está seguro de querer borrar esto permanentemente?",
    "Workflow.EMBARGOMESSAGEDATE": "Los borradores guardados de esta página se publicarán automáticamente el <a>%s</a>",
    "Workflow.EMBARGOMESSAGEDATETIME": "Los borradores guardados de esta página se publicarán automáticamente el <a>%s a las %s</a>",
    "Workflow.EMBARGOMESSAGETIME": "Los borradores guardados de esta página se publicarán automáticamente hoy a las <a>%s</a>",
    "Workflow.ProcessError": "No se pudo procesar el flujo de trabajo"
});
}