// This file was generated by silverstripe/cow from client/lang/src/it.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('it', {
    "Workflow.DeleteQuestion": "Si e' sicuri di voler eliminare definitivamente questo? ",
    "Workflow.EMBARGOMESSAGEDATE": "Le bozze salvate di questa pagina saranno auto pubblicate il <a>%s</a>",
    "Workflow.EMBARGOMESSAGEDATETIME": "Le bozze salvate di questa pagina saranno auto pubblicate il <a>%s alle %s</a>",
    "Workflow.EMBARGOMESSAGETIME": "Le bozze salvate di questa pagina saranno auto pubblicate oggi alle <a>%s</a>",
    "Workflow.ProcessError": "Impossibile processare il flusso di lavoro"
});
}