// This file was generated by silverstripe/cow from javascript/lang/src/mi.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('mi', {
    "Workflow.DeleteQuestion": "Me muku pūmau tēnei?",
    "Workflow.EMBARGOMESSAGETIME": "Ka whakaputa aunoatia anō i tēnei rā ngā hukihuki kua tiakina o tēnei whārangi <a>%s i %s</a>",
    "Workflow.EMBARGOMESSAGEDATE": "Ka whakaputa aunoatia ngā hukihuki kua tiakina o tēnei whārangi <a>%s i %s</a>",
    "Workflow.EMBARGOMESSAGEDATETIME": "Ka whakaputa aunoatia ngā hukihuki kua tiakina o tēnei whārangi <a>%s i %s</a>",
    "Workflow.ProcessError": "Kāore i taea te tukatuka te reremahi"
});
}