// This file was generated by silverstripe/cow from javascript/lang/src/ru.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ru', {
    "Workflow.DeleteQuestion": "Действительно удалить? Эта операция необратима.",
    "Workflow.EMBARGOMESSAGETIME": "Сохраненные черновики на этой странице будут автоматически опубликованы сегодня в <a>%s</a>",
    "Workflow.EMBARGOMESSAGEDATE": "Сохраненные черновики будут автоматически опубликованы <a>%s</a>",
    "Workflow.EMBARGOMESSAGEDATETIME": "Сохраненные черновики этой страницы будут автоматически опубликованы <a>%s в %s</a>",
    "Workflow.ProcessError": "Не удалось обработать поток задач"
});
}