// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/ar.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('ar', {
    "Workflow.DeleteQuestion": "هل أنت متأكد من كونك تريد حذف هذا بشكل دائم؟",
    "Workflow.EMBARGOMESSAGETIME": "سوف تنشر المسودات المحفوظة لهذه الصفحة تلقائيا اليوم في <a>%s</a>",
    "Workflow.EMBARGOMESSAGEDATE": "سوف تنشر المسودات المحفوظة لهذه الصفحة تلقائيا على <a>%s</a>",
    "Workflow.EMBARGOMESSAGEDATETIME": "سوف تنشر المسودات المحفوظة لهذه الصفحة تلقائيا على <a>%s في %s</a>",
    "Workflow.ProcessError": "لا يمكن تسيير العملية حتى النهاية"
});
}