// This file was generated by silverstripe/cow from javascript/lang/src/hr.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('hr', {
    "Workflow.DeleteQuestion": "Da li ste sigurni da želite trajno obrisati ovo?",
    "Workflow.EMBARGOMESSAGETIME": "Spremljeni draft ove stranice će biti automatski objavljen danas u <a>%s</a>",
    "Workflow.EMBARGOMESSAGEDATE": "Spremljeni draft ove stranice će biti automatski objavljen <a>%s</a>",
    "Workflow.EMBARGOMESSAGEDATETIME": "Spremljeni draft ove stranice će biti automatski objavljen <a>%s u %s</a>",
    "Workflow.ProcessError": "Ne mogu obraditi proces \"workflow\""
});
}